sudo: 'required'

services:
  - 'docker'

before_install:
  - './.travis/main.sh'

install:
  - 'make images'

script:
  - 'sudo make test'

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD ;
      make push-images ;
    fi

notifications:
  email: false

